#pragma once

#include <QSet>
#include <QFile>
#include <QAction>
#include <QString>
#include <QProcess>
#include <QVariant>
#include <QMenuBar>
#include <QToolBar>
#include <QLineEdit>
#include <QTextEdit>
#include <QClipboard>
#include <QTabWidget>
#include <QFileDialog>
#include <QTextStream>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QFileDialog>
#include <QMouseEvent>
#include <QTableWidget>
#include <QInputDialog>
#include <QApplication>
#include <QCoreApplication>
#include <QDesktopServices>
#include <QFileSystemModel>
#include <QContextMenuEvent>
